_behat_tests_page:
  pattern: /_behat/tests/page/{page}
  defaults: { _controller: MinkBundle:Tests:page }

_behat_tests_redirect:
  pattern:  /_behat/tests/redirect
  defaults: { _controller: MinkBundle:Tests:redirect }

_behat_tests_form:
  pattern:  /_behat/tests/form
  defaults: { _controller: MinkBundle:Tests:form }

_behat_tests_submit:
  pattern:  /_behat/tests/submit
  defaults: { _controller: MinkBundle:Tests:submit }

_behat_tests_headers:
  pattern:  /_behat/tests/headers
  defaults: { _controller: MinkBundle:Tests:headers }
